### PR TITLE
Add deps badge to README

### PR DESCRIPTION
**Pull request by rrrene**
Hi there,

I wanted to take a moment to pitch my latest project for the Elixir community:

  [Deps Status](https://beta.hexfaktor.org/github/elixir-addicts/rollbax)

This badge shows you an analysis for your dependencies. Behind the badge works a CI service written in Elixir which can notify you whenever important updates for your Hex packages are released.

This is still in its infancy, and I want to basically invite you to join the beta to test-drive this. I really believe that we can create a great service for the community with this. That said, don't feel any obligation to accept the PR. Just tell me what you think about this idea!

### CODE REVIEW

**Comment by whatyouhide** [comment]
I tend to be 👎 for this because I can't really see myself looking at a badge in the README of a repository I contribute to to check if deps are ok (defining what "ok" means is a whole different thing 😛). That said, I'll leave the final decision to @lexmag :)

**Comment by rrrene** [comment]
Just to clarify: You *can* get emails when updates happen (choosing between "as soon as it happens" and "give me a weekly report").

The badge is just a way to signal to potential contributors and consumers of your package that its deps are up-to-date.

**Comment by lexmag** [comment]
I agree with @whatyouhide on better not to have too much badges in README.
Service itself could be useful I guess, maybe there should be an env filtering for badge (like Travis CI does for branch) as this yellow slice means "no good" but this dep is only for test.

**Comment by rrrene** [comment]
No problem, thanks for taking the time to evaluate! :+1: 

Just for sake of completeness: There is a "prod deps only" version of the badge:   [Deps Status](https://beta.hexfaktor.org/github/elixir-addicts/rollbax) (but it is even bigger and therefore probably even less attractive :wink:)

**Pull request closed without merging**
