### PR TITLE
Allow applications to modify occurrence_data when reporting through logger

### PR DESCRIPTION
**Pull request by ono**
We would like to group some logger events into one item with `fingerprint`.

https://rollbar.com/docs/custom-grouping/

This changes allow you to set fingerprint by customising `occurrent_data`.

### CODE REVIEW

**Comment by ono** [comment]
FYI, we're using this branch on our project and working well. Let me know if you need a sample project or have any questions.

This will also let you customise other attributes like `title`, `server` etc. too.

**Comment by whatyouhide** [comment]
Hey @ono, there is a lot of ongoing work on Rollbax to fix the problem of crash logs getting reported as different items when they are symptoms of the same problem (see #62). For now, let's hold off on this PR until the rewrite of the logging part is done, and then we can revisit if we still need this (maybe we still do after all). :)

**Comment by ono** [comment]
@whatyouhide Got it. Feel free to throw this PR away if it doesn't fit with new implementation. We just want to have an extensibility on grouping errors with fingerprint. It doesn't matter how it is implemented.

Also feel free to let me know if you want me to make the change on top your work once it's done. That's also fine.

Thanks for the update!

**Comment by losco** [comment]
Hi @whatyouhide any news about the refactoring or merging this PR? We are currently using a branch of `rollbax` it will be great to know the current state of the project. Thanks!

**Comment by whatyouhide** [comment]
Hey @ono, we merged #62 and released a new version. I'm not sure this PR is needed anymore, but if you still need it, it should be reworked to work with the new architecture. I'm gonna close this off for now but feel free to comment here if you want to discuss this or still need this feature :). Thanks! 💟

**Comment by ono** [comment]
@whatyouhide that's no problem. i'll take a look next week. thanks for letting me know :+1

**Pull request closed without merging**
