### PR TITLE
Adding possibility extension of Client

### PR DESCRIPTION
**Pull request by gullitmiranda**
This enhancement allows you to extend communication with the API.

Examples of applications:
1. Customization of events.
2. Use of multiple services running on the same application.

### CODE REVIEW

**Comment by lexmag** [comment]
Thank you for the PR, could you clarify what use-cases this patch solves?

**Comment by gullitmiranda** [comment]
This PR makes it possible to create alternative client:
e.g:

```elixir
defmodule Report.Client do
  use Rollbax.Api

  defoverridable [handle_cast: 2, emit: 4]

  def emit(lvl, msg, meta, item, module_name \\ __MODULE__) do
    module_name = module_name || __MODULE__
    event = {Atom.to_string(lvl), msg, unix_timestamp(), meta, item}
    GenServer.cast(module_name, {:emit, event})
  end

  def handle_cast({:emit, _event}, %{enabled: false} = state) do
    # ...
  end

  def handle_cast({:emit, event}, %{enabled: :log} = state) do
    # ...
  end

  def handle_cast({:emit, event}, %{enabled: true} = state) do
    # ...
  end
end
```

My motivation to create this PR is to own a service (called Report) that you receive bugs from other applications (including desktop applications).

The Report application does what is needed and sends the "item" for Rollbar on a specific project.

Without this PR I can not extend the functionality of `Client` method, and the only alternative would be to duplicate it.

**Comment by lexmag** [comment]
As I see you'd like to "plug" into `emit` function to reformat/rewrite event payload.
It depends on your specific implementation of course (if you could share this bits I think it will help), but I believe it should be solved in a different way. Rather than doing that much code generation in `__using__` (it is usually a bad design sign) which together with `defoverridable` seems too magical, it'd be better to provide extra argument for start_link that represents `Formatter` (not sure about the name) behaviour.

**Comment by gullitmiranda** [comment]
Do not know.

I do not think misuse `__using__`, after all, is used in ECTO for it to be extensible. 
But I agree that we can think of a better alternative to `defoverridable` (`Formatter` or callbacks).

it's just my opinion. :smiley:

**Comment by gullitmiranda** [comment]
@lexmag, I have work to implement the `Rollbax.Plug` 
(code here: https://github.com/gullitmiranda/rollbax/tree/feature/plug).
To do this I've been thinking about how to leave the extensible `Rollbax`. Do you have any suggestion?

**Comment by lexmag** [comment]
Hey @gullitmiranda, that's wonderful, I think the proper way of making `Rollbax.Plug` would be using same logic as [`Plug.ErrorHandler`](https://github.com/elixir-lang/plug/blob/master/lib/plug/error_handler.ex) uses.

**Comment by gullitmiranda** [comment]
The branch mentioned above, I've done the whole thing work. Before closing this PR and make a new, I intend to solve the extensibility problem.

But I had an idea how to do. I want to use an option called `otp_app` well as in ECTO, Gettext and others.

eg:

```elixir
defmodule MyApp.Report do
  use Rollbax.Client, otp_app: :my_app
end
```

**Comment by lexmag** [comment]
@gullitmiranda my apology for responding late to this issue.
I think `otp_app` approach is really nice one. It seems natural and many people are familiar with it. :+1:

**Comment by gullitmiranda** [comment]
great. I'm currently doing rebase from master and making a small correction: https://github.com/elixir-addicts/rollbax/compare/master...gullitmiranda:feature/plug?expand=1
review if possible, because once finished I will do PR.

**Pull request closed without merging**
