### PR TITLE
Add catch-all clause to Rollbax.Client.handle_info/2

### LINKED ISSUE #15: Rollbax.Client function clause error on handle_info from ssl
We get occasional errors from our rollbax client crashing due to handle_info not having a catch all at the end, which is always a good idea as you don't know how the client might goof and send you weird messages ;)
```
Rollbax.Client.handle_info({:ssl, {:sslsocket, {:gen_tcp, #Port<0.28573>, :tls_connection, :undefined}, #PID<0.7686.0>}
```

### PR DESCRIPTION
**Pull request by novaugust**
Closes #15

### CODE REVIEW

**Comment by whatyouhide** [comment]
@lexmag should we log the unhandled message here?

**Comment by lexmag** [comment]
Yes, we need to log unhandled message (`info` level?), @novaugust please add this path. :bowtie:
The message mentioned in #15 looks like a something that leaks from hackney.

**Comment by whatyouhide** [comment]
Btw @novaugust, sorry I forgot to thank you for the contribution! :smile: :heart_decoration:

**Comment by novaugust** [comment]
@whatyouhide not at all, thanks for the OSS =)

Updated with logging :+1: if I'd taken more than a second to make the first change I would've seen your diligent use of Logger and been a better code chameleon, sorry about that.

**Comment by whatyouhide** [comment]
@novaugust ahah, no worries at all! :smiley_cat: Last nitpick: could you reword the commit title to say `Rollbax.Client.handle_info/2` instead of `Rollbax.Client#handle_info`?

PS I'll definitely steal your "code chameleon" expression, loved it :smile:

**Comment by novaugust** [comment]
et voila

**Comment by lexmag** [comment]
Thank you. :yellow_heart:

**Comment by novaugust** [comment]
That's a fast merge finger you've got there. Mind pinging me when this gets released to hex? I'd really appreciate it :)

**Comment by lexmag** [comment]
It's already available on Hex as v0.5.4. :smile:

**Comment by novaugust** [comment]
> It's already available on Hex as v0.5.4. 

You're a monster. Thanks!

**Pull request merged**
